from pathlib import Path
import re, shutil

base=Path('/Users/merkost/StudioProjects/Metronome')
docs=base/'docs'
logo=re.search(r'd="([^"]+)"', (docs/'logo.svg').read_text()).group(1)
icons={
'arrow':'<path d="M7 17 17 7M7 7h10v10"/>',
'right':'<path d="m9 5 7 7-7 7M4 12h12"/>',
'play':'<path d="m6 3 14 9-14 9V3Z"/>',
'stop':'<rect x="5" y="5" width="14" height="14" rx="2"/>',
'sun':'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
'moon':'<path d="M20.9 13A9 9 0 0 1 11 3.1 9 9 0 1 0 20.9 13Z"/>',
'check':'<path d="m5 12 4 4L19 6"/>',
'plus':'<path d="M12 5v14M5 12h14"/>',
'wifi-off':'<path d="m2 2 20 20M8.5 16.5a5 5 0 0 1 7 0M12 20h.01M5 12.5a10 10 0 0 1 5-2.3M16 10.7a10 10 0 0 1 3 1.8M2 8.8a15 15 0 0 1 4-2.3M10 5.1a15 15 0 0 1 12 3.7"/>',
'user':'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
'heart':'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
'volume':'<path d="m11 5-6 4H2v6h3l6 4V5ZM15.5 8.5a5 5 0 0 1 0 7M19 5a10 10 0 0 1 0 14"/>',
'globe':'<circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a18 18 0 0 1 0 20 18 18 0 0 1 0-20"/>',
'phone':'<rect x="6" y="2" width="12" height="20" rx="2"/><path d="M11 18h2"/>',
'mail':'<rect x="2" y="4" width="20" height="16" rx="2"/><path d="m2 6 10 7 10-7"/>',
'back':'<path d="m12 5-7 7 7 7M5 12h14"/>'}
symbols='<svg class="icons" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">'+''.join(f'<symbol id="i-{name}" viewBox="0 0 24 24">{path}</symbol>' for name,path in icons.items())+'</svg>'
def icon(name, cls=''):
    return f'<svg class="icon {cls}" aria-hidden="true"><use href="#i-{name}"/></svg>'
mark=f'<svg class="brand-mark" viewBox="1130 1100 5600 5400" aria-hidden="true"><path d="{logo}"/></svg>'
brand=f'<a class="brand" href="/" aria-label="Metronome home">{mark}<span>Metronome</span></a>'
header=f'''<a class="skip" href="#main">Skip to content</a>{symbols}
<header class="site-header"><div class="header-inner wrap">{brand}<nav class="nav" aria-label="Main navigation"><a href="/#practice">Practice tools</a><a href="/#get">Get the app</a><a href="support.html">Support</a></nav><div class="header-actions"><button class="icon-button theme-toggle" aria-label="Change appearance" aria-pressed="false">{icon('sun','sun')}{icon('moon','moon')}</button><a class="button small" href="app/">Open web app {icon('arrow')}</a></div></div></header>'''
footer=f'''<footer class="footer"><div class="wrap"><div class="footer-top"><div>{brand}<p class="footer-tagline">Precise timing. Better practice.</p></div><a class="studio-card" href="https://subyapp.com/" aria-label="Explore Suby, a subscription manager by Merkost"><img src="images/suby-icon.png" alt="" width="52" height="52" loading="lazy"><span class="studio-copy"><small>More by Merkost</small><strong>Suby</strong><span>Subscriptions, a little more sorted.</span></span>{icon('arrow')}</a></div><div class="footer-bottom"><nav class="footer-links" aria-label="Footer"><a href="support.html">Support</a><a href="privacy.html">Privacy</a><a href="app/">Web app</a><a href="https://merkost.dev">Made by Merkost {icon('arrow')}</a></nav><p>© 2026 Merkost</p></div></div></footer>'''
def head(title, description, canonical, home=False):
    structured='''<script type="application/ld+json">{"@context":"https://schema.org","@type":"SoftwareApplication","name":"Metronome: Practice & Tempo","operatingSystem":"iOS, Android, Web","applicationCategory":"MusicApplication","softwareVersion":"1.3.0","description":"A free metronome with practice presets, tempo and gap trainers. Core practice works offline in the installed apps.","url":"https://metronome.merkost.dev/","author":{"@type":"Person","name":"Merkost","url":"https://merkost.dev"},"offers":{"@type":"Offer","price":"0","priceCurrency":"USD"},"downloadUrl":["https://apps.apple.com/app/id6761737690","https://play.google.com/store/apps/details?id=com.merkost.metronome"]}</script>''' if home else ''
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><meta name="description" content="{description}"><link rel="canonical" href="https://metronome.merkost.dev/{canonical}"><meta name="color-scheme" content="light dark"><meta name="theme-color" content="#ffffff" media="(prefers-color-scheme:light)"><meta name="theme-color" content="#101010" media="(prefers-color-scheme:dark)"><meta property="og:type" content="website"><meta property="og:site_name" content="Metronome"><meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:url" content="https://metronome.merkost.dev/{canonical}"><meta property="og:image" content="https://metronome.merkost.dev/screenshots/og-card.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="https://metronome.merkost.dev/screenshots/og-card.png"><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="preload" href="fonts/roboto-var.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="site.css">{structured}<script type="module" src="site.js"></script></head><body>{header}'''
def faq(question,answer):
    return f'<details class="faq-item"><summary>{question}{icon("plus")}</summary><div class="faq-answer"><p>{answer}</p></div></details>'
homepage=f'''<main id="main">
<section class="hero wrap" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow marker">A little focus. A lot of rhythm.</p><h1 id="hero-title">Find your<br><span class="highlight">rhythm.</span></h1><p class="lede">A precise beat. Playful practice tools.<br>Everything you need to keep getting better.</p><div class="actions"><a class="button" href="app/">Open web app {icon('arrow')}</a><a class="button secondary" href="#get">Get the app {icon('phone')}</a></div><p class="caption">Free to play. No ads. No account.</p></div>
<div class="beat-lab" aria-label="Interactive beat preview"><div class="lab-top"><span class="eyebrow">Meet your beat</span><span class="label-pill">4 / 4</span></div><div class="pulse-art" aria-hidden="true"><span class="pulse-note">Go on, give it a play.</span>{''.join(f'<span class="pulse-dot">{i}</span>' for i in range(1,5))}</div><div class="tempo-line"><div class="tempo-readout" aria-label="80 beats per minute" role="img">{''.join(f'<span class="digit" aria-hidden="true"><span>{c}</span></span>' for c in ' 80')}</div><span class="tempo-unit">BPM</span></div><p class="tempo-marking">Andante</p><div class="slider"><span class="slider-rail" aria-hidden="true"><span class="slider-fill" style="display:block"></span></span><span class="slider-thumb" aria-hidden="true"></span><input type="range" min="40" max="220" value="80" step="1" aria-label="Preview tempo in beats per minute"></div><div class="slider-labels" aria-hidden="true"><span>40</span><span>220</span></div><div class="demo-actions"><button class="button brand-button demo-play" aria-pressed="false">{icon('play','play-icon')}{icon('stop','stop-icon')}<span class="play-label">Play a beat</span></button></div><div class="sound-choices" role="group" aria-label="Preview sound">{''.join(f'<button class="sound-choice" data-sound="{sound.lower()}" aria-pressed="{str(i==0).lower()}">{sound}</button>' for i,sound in enumerate(['Wood','Click','Classic']))}</div><p class="preview-error" role="status" hidden></p><p class="lab-foot">{icon('volume')}A small taste. The full instrument is one tap away.</p></div></section>
<div class="promise-strip wrap" aria-label="App benefits"><span class="promise">{icon('heart')}Free, without ads</span><span class="promise">{icon('user')}No account needed</span><span class="promise">{icon('wifi-off')}Offline on iOS &amp; Android</span><span class="promise">{icon('check')}40–220 BPM</span></div>
<section class="section wrap" id="practice"><div class="section-heading"><div><p class="eyebrow">More than a steady click</p><h2>Make every<br>practice count.</h2></div><p>Build speed. Hold the pulse. Give your next session a little more direction.</p></div><div class="tool-tabs" role="tablist" aria-label="Practice tools"><span class="tab-indicator" aria-hidden="true"></span>{''.join(f'<button class="tool-tab" id="tab-{key}" role="tab" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}" aria-controls="panel-{key}">{label}</button>' for i,(key,label) in enumerate([('tempo','Build speed'),('gap','Find your pulse'),('sets','Plan a session')]))}</div>
<div class="tool-panel" id="panel-tempo" role="tabpanel" aria-labelledby="tab-tempo" tabindex="0"><div class="tool-copy"><h3>Small steps.<br>Stronger playing.</h3><p>Pick a start, a target, and a step. The Tempo Trainer changes the BPM as you play, so you can focus on the passage.</p><a class="text-link" href="app/">Try Tempo Trainer {icon('right')}</a></div><div class="tool-art"><span class="tool-art-label">An example climb</span><div class="climb" aria-label="Tempo increasing from 80 to 86 BPM in steps of two"><span class="climb-step">80</span><span class="climb-step">82</span><span class="climb-step">84</span><span class="climb-step">86</span></div><span class="climb-caption">+2 BPM · every 4 bars</span></div></div>
<div class="tool-panel" id="panel-gap" role="tabpanel" aria-labelledby="tab-gap" tabindex="0" hidden><div class="tool-copy"><h3>Keep the beat.<br>Even in the quiet.</h3><p>Play a few bars. Then let the click fall silent. The Gap Trainer keeps time underneath while you build your internal pulse.</p><a class="text-link" href="app/">Try Gap Trainer {icon('right')}</a></div><div class="tool-art mint"><span class="tool-art-label">An example gap cycle</span><div class="gap-pattern" aria-label="Four audible bars followed by two silent bars">{''.join(f'<span class="gap-beat {"silent" if i>4 else ""}">{i}</span>' for i in range(1,7))}</div><span class="climb-caption">4 bars on · 2 bars quiet</span></div></div>
<div class="tool-panel" id="panel-sets" role="tabpanel" aria-labelledby="tab-sets" tabindex="0" hidden><div class="tool-copy"><h3>A plan you’ll<br>want to play.</h3><p>Save your favourite setups as presets. Arrange them into a practice set with time or bar goals. Move on when you’re ready.</p><a class="text-link" href="app/">Explore practice sets {icon('right')}</a></div><div class="tool-art pink"><span class="tool-art-label">Your next session, for example</span><div class="set-example">{''.join(f'<div class="mini-step {"current" if i==2 else ""}"><span class="step-number">{i}</span><span>{name}</span><small>{bpm} BPM</small></div>' for i,name,bpm in [(1,'Warm-up',80),(2,'Scales',100),(3,'That tricky bit',120)])}</div></div></div>
<div class="feature-line"><span>{icon('check')}Tap tempo</span><span>{icon('check')}Subdivisions &amp; accents</span><span>{icon('check')}Count-in &amp; timer</span><span>{icon('check')}Practice stats on your device</span></div></section>
<section class="section theme-section wrap" aria-labelledby="theme-title"><div class="theme-copy"><p class="eyebrow">A beat with personality</p><h2 id="theme-title">Your practice.<br>Your colour.</h2><p>Light or dark. Quiet monochrome or a little colour. Make your instrument feel like you.</p><div class="swatches" role="group" aria-label="Colour preview">{''.join(f'<button class="swatch {"mono" if key=="mono" else ""}" style="--swatch:{value}" data-name="{name}" aria-label="Preview {name}" aria-pressed="{str(key=="violet").lower()}">{icon("check")}</button>' for key,name,value in [('mono','Monochrome','#656565'),('violet','Violet','var(--violet)'),('blue','Blue','var(--blue)'),('mint','Mint','var(--mint)'),('pink','Pink','var(--pink)')])}</div><p class="theme-name" id="theme-name" aria-live="polite">Violet · preview</p></div><div class="theme-card" aria-label="Appearance preview"><div class="theme-card-top"><span class="theme-card-name">Violet</span><button class="icon-button theme-toggle" aria-label="Change appearance" aria-pressed="false">{icon('sun','sun')}{icon('moon','moon')}</button></div><div class="colour-preview" aria-hidden="true">{''.join('<span></span>' for _ in range(5))}</div><div class="theme-card-bottom"><span>Less noise. More you.</span><span>5 colour schemes</span></div></div></section>
<section class="section get-section wrap" id="get"><div class="section-heading"><div><p class="eyebrow">Wherever you practise</p><h2>Pick your stage.</h2></div><p>Jump in on the web. Keep your practice with you on your phone.</p></div><div class="get-grid"><article class="web-card">{icon('globe','platform-icon')}<h3>Right here. Right now.</h3><p>Open the full metronome in your browser. Try the trainers and find your rhythm before you install.</p><div class="actions"><a class="button" href="app/">Open web app {icon('arrow')}</a></div><p class="caption">Browser settings and presets reset when you reload. For saved practice, use the installed app.</p><p class="browser-note">Safari 18.2+, Chrome 119+, or Firefox 120+.</p></article><article class="mobile-card">{icon('phone','platform-icon')}<h3>A little practice, anywhere.</h3><p>Keep your presets, practice sets and stats on your device. Practise offline, with background playback and beat haptics.</p><div class="actions"><a class="button brand-button" href="https://apps.apple.com/app/id6761737690">iPhone &amp; iPad {icon('arrow')}</a><a class="button secondary" href="https://play.google.com/store/apps/details?id=com.merkost.metronome">Android {icon('arrow')}</a></div><p class="caption">On Android, enable Background Play in Settings.<br>Live Activities on supported iPhones.</p></article></div></section>
<section class="section questions wrap" id="questions"><div class="question-intro"><p class="eyebrow">Good questions</p><h2>A few things<br>to know.</h2><p>Something else on your mind?</p><a class="text-link" href="support.html">We’re here to help {icon('right')}</a></div><div class="faq">
{faq('Is it really free?','Yes. All the practice features are free. No advertisements, no subscription, and no account to create.')}
{faq('Can I practise offline?','Yes, with the installed iOS and Android apps. Core practice works without a network connection, and your settings and practice activity are stored on your device. The browser version needs a connection to load.')}
{faq('Will it play with my screen off?','On iPhone, playback continues with the screen off or another app open. On Android, first enable Background Play in Settings and allow its notification permission.')}
{faq('Does the web app remember my practice?','The browser version currently resets settings, presets and practice sets when you reload. Install the mobile app to keep them between sessions and use background playback and haptics.')}
{faq('Can I change the meter and sound?','Absolutely. Choose from 2/4, 3/4, 4/4, 5/4, 6/8 and 7/8, add subdivisions, and accent or mute individual beats. Wood, Click and Classic sounds are available in Settings.')}
</div></section></main>'''
(docs/'index.html').write_text(head('Metronome — Find your rhythm.','A free, ad-free metronome with tempo and gap trainers, practice sets and playful colour themes. Open the web app or get it for iPhone and Android.','',True)+homepage+footer+'</body></html>')
support=f'''<main id="main"><div class="document-head wrap"><a class="text-link" href="/">{icon('back')}Back to Metronome</a><p class="eyebrow">A little help</p><h1>Back to the beat.</h1><p class="lede">A few quick answers to keep your practice moving. If you’re stuck, send me a note.</p></div><div class="document-content wrap"><section class="contact-card"><h2>Let’s sort it out.</h2><p>Tell me what happened, your device, and your app version. A screenshot can help too.</p><a class="button" href="mailto:merkostdev+metronome@gmail.com?subject=Support%20Request%20from%20Metronome%20App">Email support {icon('mail')}</a></section><h2>Quick answers</h2><div class="faq">{faq('Playback stops when I lock the screen.','On Android, enable Background Play in Settings and allow notification permission so playback can run in the background. iPhone supports background playback automatically. The browser preview is best used with its tab open.')}{faq('How do I use tap tempo?','Tap the Tap button repeatedly at the tempo you want. After two or more taps, the BPM adjusts to your rhythm.')}{faq('How does Tempo Trainer work?','Choose a starting tempo, target tempo, step size, and how many full bars to hold between steps. The trainer changes the BPM while you play.')}{faq('Can I change the click sound?','Yes. Open Settings and choose Wood, Click or Classic.')}{faq('Why did my browser presets disappear?','The web version currently resets settings and saved practice on reload. Install the iOS or Android app to keep presets and practice sets between sessions.')}</div><a class="text-link" href="privacy.html">Read our privacy policy {icon('right')}</a></div></main>'''
(docs/'support.html').write_text(head('Support | Metronome','Quick answers and personal support for Metronome on iPhone, Android and the web.','support.html')+support+footer+'</body></html>')
privacy=(docs/'privacy.html').read_text()
legal=re.search(r'(<h2>Overview</h2>.*?)\s*<footer>',privacy,re.S).group(1)
(docs/'privacy.html').write_text(head('Privacy Policy | Metronome','How Metronome handles your settings, practice information and anonymous diagnostics.','privacy.html')+f'<main id="main"><div class="document-head wrap"><a class="text-link" href="/">{icon("back")}Back to Metronome</a><p class="eyebrow">The details</p><h1>Privacy Policy</h1><p class="caption">Last updated: September 3, 2026</p></div><div class="document-content wrap">{legal}</div></main>'+footer+'</body></html>')
error=f'<main class="error-page wrap" id="main"><p class="eyebrow">404 · A missed beat</p><h1>Let’s get<br>back in time.</h1><p class="lede">This page has wandered off. Your next practice is still right here.</p><div class="actions"><a class="button" href="/">Back to home {icon("right")}</a><a class="button secondary" href="app/">Open web app {icon("arrow")}</a></div><div class="error-art" aria-hidden="true"><span></span><span></span><span></span><span></span></div></main>'
(docs/'404.html').write_text(head('Page not found | Metronome','Find your way back to Metronome.','404.html')+error+footer+'</body></html>')
for name in ['wood.mp3','click.mp3','metronome.wav']:
    shutil.copy2(base/'shared/src/androidMain/res/raw'/name,docs/'sounds'/name)
shutil.copy2(base/'artifacts/product-review-2026-10-03/suby-icon.png',docs/'images/suby-icon.png')
print('Created homepage, support, privacy and 404 with shared branding. Privacy body preserved.')
